---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# human_populations_by_coral_reefs


Repository for the study titled "An assessment of people living by coral reefs over space and time"

## 1. Contents of repository


### `data-raw/`

Contains raw data

### `data/`

Contains coral reef buffers

### `scripts/`

Contains scripts for buffer creation, population extraction, analysis and plotting


## 2. Study workflow

Use the following scripts in order to repeat population extractions and analysis of the study

  1.**buffers.R**
    
  - Coral reef data cleaning
  - Custom function to project coral reef buffers by country
  - Buffer creation for distances (5km, 10km, 30km, 50km, 100km)
  - Buffer data cleaning
  - Coral reef country spatial dataframe
  - US buffer creation
    
  2.**population_extraction_functions.R**
    
  - Population extraction functions for use with LandScan raster data
    
  3.**population_extraction_functions_US.R**
    
  - Population extraction functions for US states associated with coral reefs
    
  4.**Population_merging_wrangling.R**
    
  - Merging population data for coral reef countries
    - Obtaining population growth values from The World Bank
  - Summarising for "world" statistics (all coral reef countries)
  - Creating dataframes for plotting:
    - Region
    - SID
    - Income_group

  5.**Plotting_main_graphs.R**
    
  - Plotting the main figures found in the study
    
  6.**Tables_df.R**
    
  - Wrangling df's to create tables for study 
    


